### ISSUE TITLE
Utilizar uma solução genérica de serviço de controle transacional;

### ISSUE THREAD

**Issue by JoabMendes** [JoabMendes/peteka#127]
Os métodos públicos de qualquer serviço serão transacionados. Além disso, se o método for de apenas leitura de dados, a transação deve ser readOnly. Caso contrário, a transação deve ser read-write.

**Comment by duartefq** [comment]
Esse bagulhinho tem nome difícil mas eh de boas, pelo que vi no repositório do professor

Sent from my BlackBerry 10 smartphone.
From: Joabe Mendes
Sent: Thursday, July 7, 2016 14:37
To: JoabMendes/peteka
Reply To: JoabMendes/peteka
Subject: [JoabMendes/peteka] Utilizar uma solução genérica de serviço de controle transacional; (#127)


Os métodos públicos de qualquer serviço serão transacionados. Além disso, se o método for de apenas leitura de dados, a transação deve ser readOnly. Caso contrário, a transação deve ser read-write.


---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/JoabMendes/peteka/issues/127

**Comment by duartefq** [comment]
Closed by  61b2c39
